# Sourced by the fetch (FOD) and the offline build derivations.  Expects:
#   $src                 repository source (read-only store path)
#   $repositoryCache     writable Bazel repository cache directory
#   $NIX_BAZELRC         the Nix-specific bazelrc (nix/bazelrc.nix)
#   $NIX_BASH            bash used for scripts with a #!/bin/bash shebang
#   $BAZEL_SERVER_JAVABASE   JDK for the Bazel server
set -euo pipefail

export HOME="$TMPDIR/home"
export BAZEL_OUTPUT_USER_ROOT="$TMPDIR/bazel-user-root"
export BAZEL_REPOSITORY_CACHE="$repositoryCache"
export USER=nixbld
export LANG=C.UTF-8 LC_ALL=C.UTF-8
mkdir -p "$HOME" "$BAZEL_OUTPUT_USER_ROOT" "$BAZEL_REPOSITORY_CACHE"

# Bazel wants a writable workspace (MODULE.bazel.lock, convenience symlinks,
# the generated build/wrapper.bazelrc), so work on a copy of the sources.
workspace="$TMPDIR/workspace"
if [[ ! -d "$workspace" ]]; then
  cp -r "$src" "$workspace"
  chmod -R u+w "$workspace"
  # tools/bazel (bazelisk hook generating build/wrapper.bazelrc) and
  # .bazelversion (BuildBuddy CLI pin) are replaced by this script and by
  # nixpkgs' Bazel; the nixpkgs bazel launcher would otherwise honour them.
  rm -f "$workspace/tools/bazel" "$workspace/.bazelversion"
  mkdir -p "$workspace/build"
  cat > "$workspace/build/wrapper.bazelrc" <<'RC'
# Generated by nix/bazel-env.sh instead of tools/bazel.
build --build_metadata=USER=nix
RC
  # Toolchain driver scripts are executed directly by Bazel actions; the Nix
  # sandbox has no /bin/bash.
  grep -rl --include='*.sh' '^#!/bin/bash' "$workspace/bazel" \
    | xargs -r sed -i "1s|^#!/bin/bash|#!$NIX_BASH/bin/bash|"
  # The mypy aspect is a lint (type checking) that pulls prebuilt binary
  # wheels (mypy, pydantic-core, ...); it is not part of the release build.
  sed -i -e '/^build --aspects=\/\/bazel\/pip:mypy.bzl%mypy_aspect$/d' \
         -e '/^build --output_groups=+mypy$/d' "$workspace/bazel/internal/common.bazelrc"
fi
cd "$workspace"

bazel_startup=(--nosystem_rc --nohome_rc
  "--server_javabase=$BAZEL_SERVER_JAVABASE"
  "--bazelrc=$NIX_BAZELRC"
  "--output_user_root=$BAZEL_OUTPUT_USER_ROOT")

# `run_bazel <command> <options...>`: runs Bazel in the workspace copy with the
# startup options above and the repository cache of this build.
run_bazel() {
  local cmd="$1"; shift
  bazel "${bazel_startup[@]}" "$cmd" "--repository_cache=$BAZEL_REPOSITORY_CACHE" "$@"
}
stop_bazel() {
  bazel "${bazel_startup[@]}" shutdown >/dev/null 2>&1 || true
}
