# The Nix-specific Bazel configuration (an extra --bazelrc file).  It carries
# everything that contains Nix store paths and therefore cannot live in
# nix/bazel-flags.nix:
#
#  * the compiler, sysroot, llvm-ifs and Python repositories Modular's build
#    would download are replaced by nixpkgs-built ones (nix/toolchain-repos.nix)
#    via --override_repository / --override_module;
#  * every linked binary gets the Nix dynamic linker and rpaths into the
#    store (glibc, libstdc++, ncurses, ...): at link time those libraries are
#    reached through the execroot-relative sysroot, at run time through the
#    store;
#  * a fixed PATH of Nix tools for actions and repository rules (Bazel's
#    strict action env would otherwise point at /bin:/usr/bin), and Nix bash
#    as the shell for genrules.
{
  lib,
  writeText,
  stdenv,
  bash,
  coreutils,
  findutils,
  gnugrep,
  gnused,
  gawk,
  diffutils,
  which,
  file,
  gnutar,
  gzip,
  bzip2,
  xz,
  zip,
  unzip,
  patch,
  git,
  python3,
  toolchainRepos,
}:
let
  system = stdenv.hostPlatform.system;
  bazelPlatform =
    {
      x86_64-linux = "x86_64-unknown-linux-gnu";
      aarch64-linux = "aarch64-unknown-linux-gnu";
    }
    .${system};
  pyMM = lib.versions.majorMinor python3.version; # 3.14
  pyTag = builtins.replaceStrings [ "." ] [ "_" ] pyMM; # 3_14
  toolPath = lib.makeBinPath [
    bash
    coreutils
    findutils
    gnugrep
    gnused
    gawk
    diffutils
    which
    file
    gnutar
    gzip
    bzip2
    xz
    zip
    unzip
    patch
    git
    python3
  ];
  # Every Python version Modular's MODULE.bazel registers is served by the one
  # nixpkgs CPython; the default toolchain is switched to that version.
  pythonVersions = [ "3_10" "3_11" "3_12" "3_13" "3_14" ];
  pythonOverrides = lib.concatMapStrings (
    v: "common --override_repository=rules_python++python+python_${v}_${bazelPlatform}=${toolchainRepos.pythonRepo}\n"
  ) pythonVersions;
in
writeText "nix.bazelrc" ''
  # Generated by nix/bazelrc.nix — Nix-native Bazel configuration.

  # nixpkgs clang 22 + lld instead of Modular's prebuilt clang tarballs.
  common --override_repository=+http_archive+clang-linux-x86_64=${toolchainRepos.clangRepo}
  common --override_repository=+http_archive+clang-linux-aarch64=${toolchainRepos.clangRepo}
  common --override_repository=+http_archive+clang-macos=${toolchainRepos.clangRepo}
  common --override_module=sysroot-jammy-x86_64=${toolchainRepos.sysrootModule "sysroot-jammy-x86_64"}
  common --override_module=sysroot-jammy-aarch64=${toolchainRepos.sysrootModule "sysroot-jammy-aarch64"}
  common --override_repository=+http_archive+llvm-ifs=${toolchainRepos.llvmIfsRepo}

  # nixpkgs CPython ${python3.version} instead of python-build-standalone.
  ${pythonOverrides}
  common --@rules_python//python/config_settings:python_version=${pyMM}

  # Nix dynamic linker + store rpaths for everything the toolchain links (the
  # sysroot is execroot-relative at link time; the store carries the runtime).
  build --linkopt=-Wl,--dynamic-linker=${toolchainRepos.dynamicLinker}
  build --host_linkopt=-Wl,--dynamic-linker=${toolchainRepos.dynamicLinker}
${lib.concatMapStrings (d: ''
  build --linkopt=-Wl,-rpath,${d}
  build --host_linkopt=-Wl,-rpath,${d}
'') toolchainRepos.runtimeLibs}
  # protobuf's protoc "authenticity check" spawns a shell without PATH (no
  # grep/cat in the Nix sandbox) to compare protoc versions; our protoc is the
  # module's own, built from source, so downgrade the check to a notice.
  build --@com_google_protobuf//bazel/toolchains:allow_nonstandard_protoc

  # gcc 15's libstdc++ headers no longer include <cstdint> transitively;
  # third-party code that relied on that (crashpad's mini_chromium) gets it
  # force-included.  (Modular's own tree and LLVM are clean.)
  build --per_file_copt=external/.*crashpad.*,-.*\.S$@-include,cstdint
  build --host_per_file_copt=external/.*crashpad.*,-.*\.S$@-include,cstdint

  # Shell and PATH for actions / repository rules.
  build --shell_executable=${bash}/bin/bash
  build --action_env=PATH=${toolPath}
  build --host_action_env=PATH=${toolPath}
  common --repo_env=PATH=${toolPath}
''
// {
  inherit toolPath pyTag;
}
