# Entry point used by flake.nix: `pkgs.callPackage ./nix { inherit self; }`.
#
# Layering (bottom-up):
#   bazel_9 (nixpkgs)    Bazel built from source by nixpkgs
#   toolchainRepos       nixpkgs clang 22/lld, sysroot module, llvm-ifs, CPython  nix/toolchain-repos.nix
#   nix.bazelrc          wires them into Modular's build (--override_*), PATH     nix/bazelrc.nix
#   modular-bazel-deps   fixed-output repository cache + lockfile (sources only)  nix/deps.nix
#   mojo-sdk-unwrapped   offline Bazel build -> SDK tree (bin/, lib/, lib/mojo/)  nix/sdk.nix
#   mojo                 SDK wrapped for use (env, cc on PATH)                     nix/mojo.nix
#   mojo-wheels          release wheels built from the SDK tree                    nix/wheels.nix
#   release              wheels + pip simple index + source tarball                nix/release.nix
{
  lib,
  pkgs,
  callPackage,
  self,
}:
let
  src = self;

  # Source tree handed to Bazel.  Everything that is not part of the Bazel
  # workspace (this packaging, flake files, CI config, top-level docs) is
  # filtered out so that editing them does not invalidate the (long) compiler
  # build; `self` still provides the git revision and the python/README files
  # used by the wheel packaging.
  buildSrc = lib.cleanSourceWith {
    name = "modular-source";
    src = self;
    filter =
      path: type:
      let
        rel = lib.removePrefix (toString self + "/") (toString path);
        top = builtins.head (lib.splitString "/" rel);
      in
      !(
        top == "nix"
        || top == "flake.nix"
        || top == "flake.lock"
        || top == ".github"
        || top == ".cursor"
        || (rel == top && lib.hasSuffix ".md" top)
      );
  };

  versions = import ./versions.nix { inherit lib src; };
  bazelFlags = import ./bazel-flags.nix { inherit lib versions; };
  seeds = callPackage ./seeds.nix { };

  bazel = pkgs.bazel_9;
  toolchainRepos = callPackage ./toolchain-repos.nix { src = buildSrc; };
  nixBazelrc = callPackage ./bazelrc.nix { inherit toolchainRepos; };

  # Output hash of the fixed-output dependency fetch, per platform.  When the
  # set of external dependencies changes, `nix build .#modular-bazel-deps`
  # reports the new value.
  depsHashes = {
    x86_64-linux = "sha256-8jG+2CMdisE549Z+2o6bl5QQPomOlcncP2UIOwBu/xM=";
    aarch64-linux = lib.fakeHash;
  };
  deps = callPackage ./deps.nix {
    inherit bazel nixBazelrc bazelFlags seeds;
    src = buildSrc;
    hash = depsHashes.${pkgs.stdenv.hostPlatform.system} or lib.fakeHash;
  };

  sdk = callPackage ./sdk.nix {
    inherit bazel nixBazelrc toolchainRepos deps bazelFlags seeds versions;
    src = buildSrc;
  };

  mojo = callPackage ./mojo.nix { inherit sdk; };

  mojoWheels = callPackage ./wheels.nix { inherit sdk src versions; };

  referenceWheels = callPackage ./reference-wheels.nix { };

  release = callPackage ./release.nix { inherit src mojoWheels versions; };

  compare = callPackage ./compare.nix { inherit mojoWheels referenceWheels; };

  # Smoke-test program for the checks.
  hello = pkgs.writeText "hello.mojo" ''
    def main():
        print("Hello from Mojo (built with Nix)!")
  '';

  # `bazel` pre-configured like the package build (nixpkgs toolchain repos,
  # PATH, ...) for use in a checkout: it calls the real Bazel binary directly,
  # so neither tools/bazel (bazelisk hook) nor .bazelversion interfere.
  bazel-nix = pkgs.writeShellApplication {
    name = "bazel-nix";
    text = ''
      if [ "''${1:-}" = "--version" ]; then exec ${bazel}/bin/bazel-${bazel.version}-linux-* --version; fi
      ws="$PWD"
      while [ ! -f "$ws/MODULE.bazel" ] && [ "$ws" != "/" ]; do ws="$(dirname "$ws")"; done
      if [ -f "$ws/MODULE.bazel" ] && [ ! -f "$ws/build/wrapper.bazelrc" ]; then
        mkdir -p "$ws/build"
        printf '# Generated by bazel-nix instead of tools/bazel.\nbuild --build_metadata=USER=nix\n' > "$ws/build/wrapper.bazelrc"
      fi
      exec ${bazel}/bin/bazel-${bazel.version}-linux-* \
        --server_javabase=${pkgs.jdk_headless} \
        --bazelrc=${nixBazelrc} "$@"
    '';
  };
in
{
  packages = {
    inherit
      bazel
      bazel-nix
      mojo
      release
      ;
    modular-bazel-deps = deps;
    mojo-sdk-unwrapped = sdk;
    mojo-wheels = mojoWheels;
    modular-clang = toolchainRepos.clangRepo;
    release-upstream-mojo = referenceWheels.reference;
    release-compare = compare;
    default = mojo;
  };

  devShells = {
    # `nix develop`: nixpkgs' Bazel pre-configured with the Nix toolchain, e.g.
    #   bazel-nix build --config=build-mojo //KGEN:mojo
    default = pkgs.mkShell {
      packages = [
        bazel-nix
        bazel
      ];
      shellHook = ''
        echo "Bazel ${bazel.version} (nixpkgs) with the Nix toolchain: bazel-nix build --config=build-mojo //KGEN:mojo"
      '';
    };
  };

  checks = {
    # Compile & run a Mojo program (JIT path).
    mojo-run = pkgs.runCommand "check-mojo-run" { nativeBuildInputs = [ mojo ]; } ''
      export HOME="$TMPDIR"
      mojo --version | tee "$out"
      mojo run ${hello} | tee -a "$out"
      grep -q "Hello from Mojo" "$out"
    '';
    # Build a native executable (exercises the `cc` link driver) and debug it.
    mojo-build = pkgs.runCommand "check-mojo-build" { nativeBuildInputs = [ mojo ]; } ''
      export HOME="$TMPDIR"
      cp ${hello} hello.mojo
      mojo build hello.mojo -o hello
      ./hello | tee "$out"
      grep -q "Hello from Mojo" "$out"
      mojo-lldb --batch -o "file hello" -o "b main" -o run -o "bt 1" -o quit 2>&1 | tee -a "$out"
      grep -q "stop reason = breakpoint" "$out"
    '';
    # The wheel writer is deterministic: two runs over the same tree must
    # produce bit-identical files.
    wheels-deterministic =
      pkgs.runCommand "check-wheels-deterministic" { nativeBuildInputs = [ pkgs.python3 ]; }
        ''
          for i in 1 2; do
            python3 ${./mkwheel.py} --name probe --version 1.0 --tag py3-none-any --purelib \
              --metadata ${pkgs.writeText "METADATA" "Metadata-Version: 2.1\nName: probe\nVersion: 1.0\n"} \
              --data platlib:${sdk}/lib=modular/lib --out out$i > /dev/null
          done
          cmp out1/*.whl out2/*.whl
          sha256sum out1/*.whl | tee "$out"
        '';
  };
}
