# The wheels Modular publishes for the release this tree corresponds to,
# pinned by URL + sha256 (see nix/release-wheels.json, generated by
# nix/update-release-wheels.py from the package index).  They are NOT part of
# the release produced by this flake — they only serve `release-compare`,
# which checks that our from-source wheels have the same shape (files, dynamic
# dependencies) as the upstream builds.
{
  lib,
  stdenvNoCC,
  fetchurl,
  linkFarm,
}:
let
  json = builtins.fromJSON (builtins.readFile ./release-wheels.json);
  system = stdenvNoCC.hostPlatform.system;
  platformTag =
    {
      x86_64-linux = "manylinux_2_34_x86_64";
      aarch64-linux = "manylinux_2_34_aarch64";
      aarch64-darwin = "macosx_13_0_arm64";
    }
    .${system} or (throw "no upstream wheels for ${system}");

  # All wheel files of a distribution that are usable on this platform.
  filesFor =
    dist:
    lib.filterAttrs (fn: _: lib.hasSuffix "-any.whl" fn || lib.hasSuffix "-${platformTag}.whl" fn) (
      json.${dist} or { }
    );

  fetchWheel =
    fn: info:
    fetchurl {
      name = fn;
      url = info.url;
      sha256 = info.sha256;
    };
in
{
  inherit json platformTag filesFor fetchWheel;

  # Upstream builds of what this flake builds from source (for comparison).
  reference = linkFarm "modular-release-upstream-mojo" (
    lib.concatMap
      (
        dist: lib.mapAttrsToList (fn: info: { name = fn; path = fetchWheel fn info; }) (filesFor dist)
      )
      [
        "mojo"
        "mojo-compiler"
        "mojo-compiler-mojo-libs"
        "mojo-lldb-libs"
        "mblack"
      ]
  );
}
